date.timezone = "Asia/Tokyo"
safe_mode=Off
post_max_size=10M
upload_max_filesize=10M
memory_limit=512M
max_execution_time=600

; PCOV: enabled to collect coverage; set to 0 for runs that don't need coverage
pcov.enabled=1
pcov.directory=/var/www/exment